a=[1,5,19,21,8,6]
print(max(a))
print(min(a))
print(a.sort())
print(len(a))
print(a.pop())
print(a)
print(a.append(9))
print(a)
print(a.extend([4,17,12]))
print(a)
print(a.reverse())
print(a)
print(sum(a))
print(a.insert(5,20))
print(a)
print(a.remove(12))
print(a)
print(a.count(9))
print(a.clear())
print(a)
name=["Saro","(Sudar","Hari","Harsha","Sudar"]
print(name.sort())
print(name)
print(max(name))
print(min(name))
print(name.count("Sudar"))



